import { defineConfig } from 'vitepress';

const REPO = 'https://github.com/aileo/pensa';

export default defineConfig({
  title: 'Pensa',
  description: 'Organize family gifts without carrying it all in your head.',
  lang: 'en',
  // The site is served from https://aileo.github.io/pensa/.
  base: '/pensa/',
  cleanUrls: true,
  // The pages the site renders are copies, so their git history lives under a
  // different path — a "last updated" stamp read from them would be wrong.
  lastUpdated: false,
  // A link that does not resolve is a link nobody will fix later — except the
  // addresses the documentation tells you to open on your own machine, which no
  // build server will ever reach.
  ignoreDeadLinks: [/^https?:\/\/localhost(:\d+)?/],
  head: [
    ['meta', { name: 'theme-color', content: '#8c4d57' }],
    ['meta', { property: 'og:title', content: 'Pensa' }],
    [
      'meta',
      {
        property: 'og:description',
        content: 'Organize family gifts without carrying it all in your head.',
      },
    ],
  ],
  themeConfig: {
    nav: [
      { text: 'User guide', link: '/docs/user-guide' },
      { text: 'Deploy', link: '/docs/deployment' },
      { text: 'Develop', link: '/docs/development' },
      { text: 'Changelog', link: '/changelog' },
    ],
    sidebar: [
      {
        text: 'Using Pensa',
        items: [
          { text: 'User guide (English)', link: '/docs/user-guide' },
          { text: 'Guide utilisateur (français)', link: '/docs/guide-utilisateur' },
          { text: 'Features', link: '/docs/features' },
        ],
      },
      {
        text: 'Running an instance',
        items: [{ text: 'Deployment', link: '/docs/deployment' }],
      },
      {
        text: 'Contributing',
        items: [
          { text: 'How to contribute', link: '/docs/CONTRIBUTING' },
          { text: 'Development guide', link: '/docs/development' },
          { text: 'Working on the repository', link: '/agent' },
          { text: 'API reference', link: '/docs/api' },
          { text: 'Design system', link: '/docs/design-system' },
          { text: 'Testing guide', link: '/docs/testing-guide' },
        ],
      },
      {
        text: 'Releases',
        items: [{ text: 'Changelog', link: '/changelog' }],
      },
    ],
    socialLinks: [{ icon: 'github', link: REPO }],
    editLink: {
      pattern: `${REPO}/edit/main/:path`,
      text: 'Edit this page on GitHub',
    },
    search: { provider: 'local' },
    outline: [2, 3],
    footer: {
      message: 'Entirely generated by AI, directed by a human. MIT licensed.',
      copyright: `<a href="${REPO}">aileo/pensa</a>`,
    },
  },
  // Most pages are copied out of docs/ and keep the same path, so the edit
  // link lands on the real source. The few that are renamed on the way in do
  // not, and an edit link pointing at a file that does not exist is worse than
  // none.
  transformPageData(pageData) {
    const renamed = ['agent.md', 'changelog.md', 'docs/index.md', 'index.md'];
    if (renamed.includes(pageData.relativePath)) {
      pageData.frontmatter.editLink = false;
    }
  },
});
